# Generated by Django 6.0.4 on 2026-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_salary', models.FloatField()),
            ],
        ),
    ]
